<?
$PERM["statistic_na"]["10"]="X";
$PERM["statistic_na"]["*"]="D";
$PERM["bitrix"]["8"]="R";
$PERM["bitrix"]["7"]="R";
$PERM["bitrix"]["6"]="R";
$PERM["bitrix"]["9"]="R";
$PERM["about"]["9"]="W";
$PERM["contacts_old"]["5"]="W";
$PERM["/"]["*"]="R";
$PERM["oprosy"]["7"]="W";
$PERM["rew"]["6"]="W";
$PERM["testovyy-razdel"]["2"]="D";
$PERM["testovyy-razdel"]["3"]="D";
$PERM["testovyy-razdel"]["4"]="D";
$PERM["testovyy-razdel"]["5"]="D";
$PERM["testovyy-razdel"]["*"]="D";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["index.php"]["5"]="W";
?>